---
title: "Research Proposal"
author: "Eungwon Lee"

execute:
  echo: false
  
bibliography: references.bib
---

> **Abstract.**  
>
> **Keywords.** SVAR, monetary policy, credit, deposit

#  The objective, question, and motivation

## Objective

The research objective is to investigate the relationship among monetary policy, banks deposit and credit growth, while considering other important macroeconomic variables in Australia, using a structural vector autoregression model.

## Research question

How does the monetary policy and deposit growth affect the banks' credit growth in Australia?

## Motivation

Banks' credit plays an important role in the economy as it supports investment for firms, consumption for households, and sometimes causes inflationary pressure. Thus, the effect of monetary policy on credit has been deemed to be an important concern for researchers and central bankers. One channel that explains how monetary policy works through credit is called the credit channel. In the credit channel, changes in monetary policy affect the required reserves of banks, which cause banks to change the quantity of loans they provide (e.g., Bernanke and Blinder 1992; Jimenez et al. 2014). However, the effect of changes in reserves has been estimated to be too small to exert a meaningful influence on bank lending (Woodford 2010). One suggestion to fill this gap is proposed by Dreschler et al. (2017). In the paper, they argue that banks' credit substantially reacts to monetary policy through changes in deposits. According to their estimation, it accounts for the entire transmission of monetary policy through the bank's balance sheet. I incorporate this deposit channel in the SVAR framework to evaluate the effect of monetary policy and deposit change on banks' credit.


#  Data

Following Berkelmans(2005), variables are largely divided into two groups: the external and domestic sector. For the external sector, real commodity prices (or oil prices), and real US GDP are used. The domestic sector is captured by real Australian GDP, inflation rate, banks credit, deposit, US exchange rate, and cash rate.





## References {.unnumbered}

